export const RECIPES_GETALL_REQUEST = 'RECIPES_GETALL_REQUEST'
export const RECIPES_GETALL_SUCCESS = 'RECIPES_GETALL_SUCCESS'
export const RECIPES_GETALL_FAILURE = 'RECIPES_GETALL_FAILURE'
export const RECIPES_CHANGE_URL = 'RECIPES_CHANGE_URL'

export const MYBOOKS_GETALL_REQUEST = 'MYBOOKS_GETALL_REQUEST'
export const MYBOOKS_GETALL_SUCCESS = 'MYBOOKS_GETALL_SUCCESS'
export const MYBOOKS_GETALL_FAILUER = 'MYBOOKS_GETALL_FAILUER'